[package]
authors = ["Casey Primozic <me@ameo.link>"]
build = "build.rs"
name = "game-engine"
version = "0.1.0"

[build-dependencies]
protobuf-codegen-pure = "2.0.3"

[dependencies]
palette = "0.4.0"
protobuf = "2.0.4"

[dependencies.uuid]
features = ["u128"]
version = "0.6.5"

[dependencies.wasm-bindgen]
git = "https://github.com/rustwasm/wasm-bindgen.git"
rev = "315b5d848ee6c2383a602178364cbe359be664b8"

[lib]
crate-type = ["cdylib"]

[profile.dev]
lto = false
opt-level = 3

[profile.release]
lto = true
panic = 'abort'

