[package]
authors = ["Casey Primozic <me@ameo.link>"]
name = "game-engine"
uild = "build.rs"
version = "0.1.0"

[build-dependencies]
protobuf-codegen-pure = "2.0.3"

[dependencies]
lazy_static = "1.0.2"
protobuf = "2.0.4"
uuid = { version = "0.6.5", features = ["u128"] }

[dependencies.wasm-bindgen]
git = "https://github.com/rustwasm/wasm-bindgen.git"
rev = "315b5d848ee6c2383a602178364cbe359be664b8"

[lib]
crate-type = ["cdylib"]
