[package]
authors = ["Casey Primozic <me@ameo.link>"]
build = "build.rs"
name = "game-engine"
version = "0.1.0"

[build-dependencies]
protobuf-codegen-pure = "2.0.3"

[dependencies]
protobuf = "2.0.4"
serde = "1.0.70"
serde_derive = "1.0.70"

[dependencies.uuid]
features = ["u128"]
version = "0.6.5"

[dependencies.wasm-bindgen]
features = ["serde-serialize"]
git = "https://github.com/rustwasm/wasm-bindgen.git"
rev = "64591ef4038108104a10fbde62670f3232e76960"

[lib]
crate-type = ["cdylib"]

[profile]

[profile.dev]
lto = false
opt-level = 3

[profile.release]
lto = true
panic = "abort"
