[package]
authors = ["Casey Primozic <me@ameo.link>"]
name = "game-engine"
build = "build.rs"
version = "0.1.0"

[build-dependencies]
protobuf-codegen-pure = "2.0.3"

[dependencies]
lazy_static = "1.0.2"
palette = "0.4.0"
protobuf = "2.0.4"
rand = { version="0.4.2", features=["i128_support"]}

[dependencies.uuid]
features = ["u128"]
version = "0.6.5"

[dependencies.wasm-bindgen]
git = "https://github.com/rustwasm/wasm-bindgen.git"
rev = "315b5d848ee6c2383a602178364cbe359be664b8"

[lib]
crate-type = ["cdylib"]
